services:
  - type: web
    name: studybuddy-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_KEY_PATH
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PORT
        value: 10000
      - key: DATABASE
        value: /app/data/feedback.db
      - key: CHROMA_PATH
        value: /app/chromadb
    disks:
      - name: data
        mountPath: /app/data
        sizeGB: 1
      - name: chromadb
        mountPath: /app/chromadb
        sizeGB: 1